"""initial schema

Revision ID: 36c09c77da99
Revises: b455cf9da14b
Create Date: 2026-09-24 14:08:59.801476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c09c77da99'
down_revision: Union[str, Sequence[str], None] = 'b455cf9da14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column('staff_id',
                existing_type=sa.VARCHAR(),
                nullable=True)
        batch_op.alter_column('Street_address',
                new_column_name="street_address",
                existing_type=sa.VARCHAR(),
                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Street_address', sa.VARCHAR(), nullable=False))
    op.alter_column('users', 'staff_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'street_address')
    # ### end Alembic commands ###
